### PR TITLE
Add form in order to add tasks

### PR DESCRIPTION
**Pull request by dlumbrer**
This PR adds the functionality in the UI and backend part of adding task via form. 

---

In order to test it, follow the next steps:

1. Install dependencies and build the ui app (inside the ui folder)
```bash

raistlin/ui $> yarn install
raistlin/ui $> yarn build

```

2. Python requeriments and launch django server:

```bash
raistlin $> pip3 install -r requeriments.txt
raistlin $> python manage.py migrate --settings=config.settings.devel
raistlin $> python manage.py makemigrations --settings=config.settings.devel
raistlin $> python manage.py runserver --settings=config.settings.devel
```

### CODE REVIEW

**Comment by sduenas** [comment]
When I add a new task I get this error in Arthur once it starts running on a worker:
```
[2019-09-03 16:30:43,419] - AttributeError: ('required argument uri not found', 'uri')
Traceback (most recent call last):
  File "/home/sduenas/devel/venv/lib/python3.6/site-packages/rq/worker.py", line 812, in perform_job
    rv = job.perform()
  File "/home/sduenas/devel/venv/lib/python3.6/site-packages/rq/job.py", line 588, in perform
    self._result = self._execute()
  File "/home/sduenas/devel/venv/lib/python3.6/site-packages/rq/job.py", line 594, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/home/sduenas/devel/grimoirelab/kingarthur/arthur/jobs.py", line 303, in execute_perceval_job
    raise e
  File "/home/sduenas/devel/grimoirelab/kingarthur/arthur/jobs.py", line 301, in execute_perceval_job
    job.run(backend_args, archive_args=archive_args, resume=resume)
  File "/home/sduenas/devel/grimoirelab/kingarthur/arthur/jobs.py", line 200, in run
    for item in self._execute(args, archive_args):
  File "/home/sduenas/devel/grimoirelab/kingarthur/arthur/jobs.py", line 59, in decorator
    for item in func(self, *args, **kwargs):
  File "/home/sduenas/devel/grimoirelab/perceval/perceval/backend.py", line 566, in fetch
    backend_args)
  File "/home/sduenas/devel/venv/src/grimoirelab-toolkit/grimoirelab_toolkit/introspect.py", line 95, in find_signature_parameters
    raise AttributeError(msg, name)
AttributeError: ('required argument uri not found', 'uri')
Traceback (most recent call last):
  File "/home/sduenas/devel/venv/lib/python3.6/site-packages/rq/worker.py", line 812, in perform_job
    rv = job.perform()
  File "/home/sduenas/devel/venv/lib/python3.6/site-packages/rq/job.py", line 588, in perform
    self._result = self._execute()
  File "/home/sduenas/devel/venv/lib/python3.6/site-packages/rq/job.py", line 594, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/home/sduenas/devel/grimoirelab/kingarthur/arthur/jobs.py", line 303, in execute_perceval_job
    raise e
  File "/home/sduenas/devel/grimoirelab/kingarthur/arthur/jobs.py", line 301, in execute_perceval_job
    job.run(backend_args, archive_args=archive_args, resume=resume)
  File "/home/sduenas/devel/grimoirelab/kingarthur/arthur/jobs.py", line 200, in run
    for item in self._execute(args, archive_args):
  File "/home/sduenas/devel/grimoirelab/kingarthur/arthur/jobs.py", line 59, in decorator
    for item in func(self, *args, **kwargs):
  File "/home/sduenas/devel/grimoirelab/perceval/perceval/backend.py", line 566, in fetch
    backend_args)
  File "/home/sduenas/devel/venv/src/grimoirelab-toolkit/grimoirelab_toolkit/introspect.py", line 95, in find_signature_parameters
    raise AttributeError(msg, name)
AttributeError: ('required argument uri not found', 'uri')
```

**Comment by dlumbrer** [comment]
There were a typo in the code, sorry.

PR updated @sduenas

**Comment by sduenas** [comment]
> There was a typo in the code, sorry.
> 
> PR updated @sduenas

That fixed the problem with Git. It works fine. I found this error with bugzilla, though:

```
[04/Sep/2019 14:22:59] "GET /?selectbackend=bugzillarest&selectBugzillarestCategory=bug HTTP/1.1" 200 959
Internal Server Error: /tasks/add_task
Traceback (most recent call last):
  File "/home/sduenas/devel/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/sduenas/devel/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/sduenas/devel/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/sduenas/devel/venv/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/sduenas/devel/venv/lib/python3.6/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/sduenas/devel/venv/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/sduenas/devel/grimoirelab/raistlin/raistlin/tasks/views.py", line 55, in dispatch
    return super(AddTask, self).dispatch(*args, **kwargs)
  File "/home/sduenas/devel/venv/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/sduenas/devel/grimoirelab/raistlin/raistlin/tasks/views.py", line 75, in post
    'url': task_data['bugzillaBackendArgs']['url'],
KeyError: 'bugzillaBackendArgs
```

**Comment by sduenas** [comment]
Btw, I think once you add a task, the form should redirect to the view with the new task.

**Comment by dlumbrer** [comment]
PR updated, I didn't notice the error, sorry

> Btw, I think once you add a task, the form should redirect to the view with the new task.

Yes, this is included, but just when the task is added successfully.

**Comment by sduenas** [comment]
Now it works but it redirects to the main tasks page. I think it will be better if it redirects to the task that was already created.

**Comment by dlumbrer** [comment]
> Now it works but it redirects to the main tasks page. I think it will be better if it redirects to the task that was already created.

Done! I thought that you meant to the tasks view :sweat_smile:

**Pull request closed without merging**
